name: Release CD

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6.0.3

      - name: Create build folder
        run: mkdir -p dist

      - name: Build release package
        run: |
          echo "Creating release package..."
          tar -czf dist/release-${{ github.ref_name }}.tar.gz .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          files: dist/release-${{ github.ref_name }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
